# Generated by Django 2.2.5 on 2019-09-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstracttypedir',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='abstracttypedir',
            name='updated_at',
        ),
    ]
