# Generated by Django 2.2.5 on 2019-09-28 06:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('is_from', models.SmallIntegerField(blank=True, choices=[(1, 'Trudvsem'), (2, 'hh.ru')], null=True, verbose_name='Откуда получены данные')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название работадателя')),
                ('ogrn', models.CharField(blank=True, max_length=56, null=True, verbose_name='ОГРН')),
                ('companycode', models.CharField(blank=True, max_length=56, null=True, verbose_name='ID service')),
                ('inn', models.CharField(blank=True, max_length=56, null=True, verbose_name='ИНН')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ident', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_from', models.SmallIntegerField(blank=True, choices=[(1, 'Trudvsem'), (2, 'hh.ru')], null=True, verbose_name='Откуда получины данные')),
                ('id_service', models.CharField(blank=True, max_length=55, null=True, verbose_name='id')),
                ('created_dt', models.DateField(blank=True, null=True, verbose_name='Дата создания на сервисе')),
                ('salary', models.CharField(blank=True, max_length=50, null=True, verbose_name='Зарплата')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Минимальная ЗП')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')),
                ('employment', models.CharField(blank=True, max_length=55, null=True, verbose_name='Трудоустройство')),
                ('schedule', models.CharField(blank=True, max_length=55, null=True, verbose_name='График работы')),
                ('duty', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('education', models.CharField(blank=True, max_length=150, verbose_name='Образование')),
                ('qualification', models.TextField(blank=True, null=True, verbose_name='Квалификация')),
                ('experience', models.CharField(blank=True, max_length=55, null=True, verbose_name='Опыт работы')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Category', verbose_name='Категория')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Employer', verbose_name='Работадатель')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('professions', models.ManyToManyField(to='vacancy.Profession')),
            ],
        ),
    ]
